### ISSUE TITLE
3.3.0 hangs when duplicate material - memory consumption grows

### ISSUE THREAD

**Issue by RodLaird** [BCN3D/Cura#161]
**Application Version**
3.3.0
**Platform**
Windows 10 x64

**Qt**

**PyQt**

**Display Driver**

**Steps to Reproduce**
Duplicate a material. First time seems ok. Repeat and eventually the programme hangs

**Actual Results**
one CPU core locks up and memory grows continuously

**Expected results**
should just get a duplicate material to edit!

**Additional Information**
tried reinstall and deletion of %appdata% files. Ran Procmon to track error which is included in attached .rar file - along with the Cura log which shows lots of:
2020-10-22 10:55:44,197 - ERROR - [(31272)-MainThread] UM.Logger.logException [86]: IndexError: list index out of range
2020-10-22 10:55:44,200 - ERROR - [(31272)-MainThread] UM.Logger.logException [86]: Traceback (most recent call last):
2020-10-22 10:55:44,201 - ERROR - [(31272)-MainThread] UM.Logger.logException [86]:   File "C:\workspace\cura-build\build\inst\lib\python3.5\site-packages\UM\Settings\ContainerRegistry.py", line 178, in findContainers
2020-10-22 10:55:44,202 - ERROR - [(31272)-MainThread] UM.Logger.logException [86]:   File "D:\Program Files\BCN3D Cura 3.3\plugins\LocalContainerProvider\LocalContainerProvider.py", line 69, in loadContainer
2020-10-22 10:55:44,204 - ERROR - [(31272)-MainThread] UM.Logger.logException [86]:     return ContainerRegistry.getInstance().findContainers(id = container_id)[0]

and then lots of:
2020-10-22 10:57:14,762 - DEBUG - [(31272)-MainThread] LocalContainerProvider.LocalContainerProvider.loadContainer [50]: Loading container generic_pla
2020-10-22 10:57:14,763 - DEBUG - [(31272)-MainThread] XmlMaterialProfile.XmlMaterialProfile.deserialize [544]: Found definition for machine ID bcn3dsigma
2020-10-22 10:57:14,787 - DEBUG - [(31272)-MainThread] XmlMaterialProfile.XmlMaterialProfile.deserialize [544]: Found definition for machine ID bcn3dsigmar19
2020-10-22 10:57:15,619 - DEBUG - [(31272)-MainThread] XmlMaterialProfile.XmlMaterialProfile.deserialize [544]: Found definition for machine ID bcn3depsilon
2020-10-22 10:57:15,627 - DEBUG - [(31272)-MainThread] XmlMaterialProfile.XmlMaterialProfile.deserialize [544]: Found definition for machine ID bcn3dw27
2020-10-22 10:57:15,638 - DEBUG - [(31272)-MainThread] XmlMaterialProfile.XmlMaterialProfile.deserialize [544]: Found definition for machine ID bcn3dd25

[Cura 3.3 bug.zip](https://github.com/BCN3D/Cura/files/5419265/Cura.3.3.bug.zip)

**Comment by marcmateo** [comment]
Hello, 

We are already working on it to be able to have it solved in the following versions.

Thanks for reporting the issue.
