### ISSUE TITLE
Error launching AppImage on Debian

### ISSUE THREAD

**Issue by mntmn** [BCN3D/Cura#52]
I want to use my Sigma with Debian Linux. I downloaded BCN3D.Cura-1.1.0-beta.AppImage and made it executable. When I start it, the following error messages appear:

```
% ./BCN3D.Cura-1.1.0-beta.AppImage 
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/epardo/Documents/Projects/Cura2/cura-build-environment/install_dir/lib/python3.5/site-packages/cx_Freeze/initscripts/__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/epardo/Documents/Projects/Cura2/cura-build-environment/install_dir/lib/python3.5/site-packages/cx_Freeze/initscripts/Console.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/epardo/Documents/Projects/Cura2/cura-build/build/inst/bin/cura", line 19, in <module>
  File "/home/epardo/Documents/Projects/Cura2/cura-build-environment/install_dir/lib/python3.5/ctypes/__init__.py", line 347, in __init__
OSError: /usr/lib/x86_64-linux-gnu/libGL.so.1: undefined symbol: __GLXGL_CORE_FUNCTIONS
```

My platform is:

```
Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
Debian Version 9.1
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ivybridge Mobile 
OpenGL core profile version string: 3.3 (Core Profile) Mesa 13.0.6
OpenGL core profile shading language version string: 3.30
```

Any hints are appreciated.

**Comment by eloipr** [comment]
I would try to update you graphic card drivers.
